
package com.mycompany.behappy;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author AANISHA BHATTACHARYA
 */


public class TakeTestUI extends javax.swing.JFrame {

    /**
     * Creates new form TakeTestUI
     */
    
    private TakeTestEntity ent;
    private int Stsc = 0;
    private int Ansc = 0;
    private int Desc = 0;
    private DisplayManager mgr;

    public TakeTestUI(DisplayManager mgr) {
        this.mgr = mgr;

        initComponents();
//        this.setSize(new Dimension(900, 650));
        this.setLocationRelativeTo(null);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane1.getHorizontalScrollBar().setUnitIncrement(8);
        ent = new TakeTestEntity();
        stressScreen();
        //this.jPanel6.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        take_test = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(40, 153, 160));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 6, new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Take Test");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/logo_full.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/arrow.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/home.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(135, 135, 135)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(147, 205, 186));

        jPanel3.setBackground(new java.awt.Color(147, 205, 186));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 88, 81));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Take Test");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(147, 205, 186));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(2);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jTextArea2.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(147, 205, 186));

        take_test.setBackground(new java.awt.Color(40, 153, 160));
        take_test.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        take_test.setForeground(new java.awt.Color(255, 255, 255));
        take_test.setText("Take Test");
        take_test.setBorder(null);
        take_test.setFocusPainted(false);
        take_test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                take_testMouseClicked(evt);
            }
        });
        take_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                take_testActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jPanel6.setBackground(new java.awt.Color(147, 205, 186));
        jPanel6.setForeground(new java.awt.Color(0, 102, 51));
        jPanel6.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("jLabel3");

        jRadioButton1.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("All of the time");

        jRadioButton2.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Most of the time");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("A litlle of the time");

        jRadioButton4.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("None of the time");

        jLabel4.setBackground(new java.awt.Color(147, 205, 186));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("jLabel4");

        jRadioButton5.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("All of the time");

        jRadioButton6.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Most of the time");

        jRadioButton7.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("A little of the time");

        jRadioButton8.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("None of the time");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("jLabel5");

        jRadioButton9.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("All of the time");

        jRadioButton10.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("Most of the time");

        jRadioButton11.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("A little of the time");

        jRadioButton12.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("None of the time");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setText("jLabel6");

        jRadioButton13.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup4.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("All of the time");

        jRadioButton14.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("Most of the time");

        jRadioButton15.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup4.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("A little of the time");

        jRadioButton16.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup4.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("None of the time");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText("jLabel7");

        jRadioButton17.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup5.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton17.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setText("All of the time");

        jRadioButton18.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup5.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton18.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setText("Most of the time");

        jRadioButton19.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup5.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton19.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setText("A little of the time");

        jRadioButton20.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup5.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton20.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton20.setText("None of the time");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("jLabel8");

        jRadioButton21.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup6.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton21.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton21.setText("All of the time");

        jRadioButton22.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup6.add(jRadioButton22);
        jRadioButton22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton22.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton22.setText("Most of the time");

        jRadioButton23.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup6.add(jRadioButton23);
        jRadioButton23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton23.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton23.setText("A little of the time");

        jRadioButton24.setBackground(new java.awt.Color(147, 205, 186));
        buttonGroup6.add(jRadioButton24);
        jRadioButton24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton24.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton24.setText("None of the time");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton19, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addComponent(jRadioButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                .addComponent(jRadioButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                .addComponent(jRadioButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                                .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                                .addComponent(jRadioButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jRadioButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton24)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(take_test, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(742, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(take_test, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void stressScreen() {
        this.jLabel1.setText("Stress Test");
        this.jPanel6.setVisible(true);
        take_test.setText("Submit Stress Test");

        this.jTextArea2.setText("Answer the questions below");
        this.jLabel3.setText("In last week " + mgr.BHM.TTMgr.getStress(0));
        this.jLabel4.setText("In last week " + mgr.BHM.TTMgr.getStress(1));
        this.jLabel5.setText("In last week " + mgr.BHM.TTMgr.getStress(2));
        this.jLabel6.setText("In last week " + mgr.BHM.TTMgr.getStress(3));
        this.jLabel7.setText("In last week " + mgr.BHM.TTMgr.getStress(4));
        this.jLabel8.setText("In last week " + mgr.BHM.TTMgr.getStress(5));
    }
    private void take_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_take_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_take_testActionPerformed

    private void take_testMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_take_testMouseClicked
        // TODO add your handling code here:
        jScrollPane1.getViewport().setViewPosition(new Point(0,0));
        String label = this.take_test.getText();
        /*if(label.equalsIgnoreCase("Take Test"))
        {
           
            
            
        }*/
        if (label.equalsIgnoreCase("Submit Stress Test")) {
            if ((this.buttonGroup1.isSelected(this.jRadioButton1.getModel()) || this.buttonGroup1.isSelected(this.jRadioButton2.getModel()) || this.buttonGroup1.isSelected(this.jRadioButton3.getModel()) || this.buttonGroup1.isSelected(this.jRadioButton4.getModel())) && (this.buttonGroup2.isSelected(this.jRadioButton5.getModel()) || this.buttonGroup2.isSelected(this.jRadioButton6.getModel()) || this.buttonGroup2.isSelected(this.jRadioButton7.getModel()) || this.buttonGroup2.isSelected(this.jRadioButton8.getModel())) && (this.buttonGroup3.isSelected(this.jRadioButton9.getModel()) || this.buttonGroup3.isSelected(this.jRadioButton10.getModel()) || this.buttonGroup3.isSelected(this.jRadioButton11.getModel()) || this.buttonGroup3.isSelected(this.jRadioButton12.getModel())) && (this.buttonGroup4.isSelected(this.jRadioButton13.getModel()) || this.buttonGroup4.isSelected(this.jRadioButton14.getModel()) || this.buttonGroup4.isSelected(this.jRadioButton15.getModel()) || this.buttonGroup4.isSelected(this.jRadioButton16.getModel())) && (this.buttonGroup5.isSelected(this.jRadioButton17.getModel()) || this.buttonGroup5.isSelected(this.jRadioButton18.getModel()) || this.buttonGroup5.isSelected(this.jRadioButton19.getModel()) || this.buttonGroup5.isSelected(this.jRadioButton20.getModel())) && (this.buttonGroup6.isSelected(this.jRadioButton21.getModel()) || this.buttonGroup6.isSelected(this.jRadioButton22.getModel()) || this.buttonGroup6.isSelected(this.jRadioButton23.getModel()) || this.buttonGroup6.isSelected(this.jRadioButton24.getModel()))) {
                if ((this.buttonGroup1.isSelected(this.jRadioButton1.getModel()))) {
                    Stsc += 3;
                } else if ((this.buttonGroup1.isSelected(this.jRadioButton2.getModel()))) {
                    Stsc += 2;
                } else if ((this.buttonGroup1.isSelected(this.jRadioButton3.getModel()))) {
                    Stsc += 1;
                } else if ((this.buttonGroup1.isSelected(this.jRadioButton4.getModel()))) {
                    Stsc += 0;
                }
                if ((this.buttonGroup2.isSelected(this.jRadioButton5.getModel()))) {
                    Stsc += 3;
                } else if ((this.buttonGroup2.isSelected(this.jRadioButton6.getModel()))) {
                    Stsc += 2;
                } else if ((this.buttonGroup2.isSelected(this.jRadioButton7.getModel()))) {
                    Stsc += 1;
                } else if ((this.buttonGroup2.isSelected(this.jRadioButton8.getModel()))) {
                    Stsc += 0;
                }
                if ((this.buttonGroup3.isSelected(this.jRadioButton9.getModel()))) {
                    Stsc += 3;
                } else if ((this.buttonGroup3.isSelected(this.jRadioButton10.getModel()))) {
                    Stsc += 2;
                } else if ((this.buttonGroup3.isSelected(this.jRadioButton11.getModel()))) {
                    Stsc += 1;
                } else if ((this.buttonGroup3.isSelected(this.jRadioButton12.getModel()))) {
                    Stsc += 0;
                }
                if ((this.buttonGroup4.isSelected(this.jRadioButton13.getModel()))) {
                    Stsc += 3;
                } else if ((this.buttonGroup4.isSelected(this.jRadioButton14.getModel()))) {
                    Stsc += 2;
                } else if ((this.buttonGroup4.isSelected(this.jRadioButton15.getModel()))) {
                    Stsc += 1;
                } else if ((this.buttonGroup4.isSelected(this.jRadioButton16.getModel()))) {
                    Stsc += 0;
                }
                if ((this.buttonGroup5.isSelected(this.jRadioButton17.getModel()))) {
                    Stsc += 3;
                } else if ((this.buttonGroup5.isSelected(this.jRadioButton18.getModel()))) {
                    Stsc += 2;
                } else if ((this.buttonGroup5.isSelected(this.jRadioButton19.getModel()))) {
                    Stsc += 1;
                } else if ((this.buttonGroup5.isSelected(this.jRadioButton20.getModel()))) {
                    Stsc += 0;
                }
                if ((this.buttonGroup6.isSelected(this.jRadioButton21.getModel()))) {
                    Stsc += 3;
                } else if ((this.buttonGroup6.isSelected(this.jRadioButton22.getModel()))) {
                    Stsc += 2;
                } else if ((this.buttonGroup6.isSelected(this.jRadioButton23.getModel()))) {
                    Stsc += 1;
                } else if ((this.buttonGroup6.isSelected(this.jRadioButton24.getModel()))) {
                    Stsc += 0;
                }

                this.jLabel1.setText("Anxiety test");
                take_test.setText("Submit Anxiety Test");
                this.jTextArea2.setText("Answer the questions below");
                this.jLabel3.setText("In the past 2 weeks, how often " + mgr.BHM.TTMgr.getAnxiety(0));
                this.jLabel4.setText("In the past 2 weeks, how often " + mgr.BHM.TTMgr.getAnxiety(1));
                this.jLabel5.setText("In the past 2 weeks, how often did you fear,being over-worked?");
                this.jLabel6.setText("In the past 2 weeks, how often " + mgr.BHM.TTMgr.getAnxiety(3));
                this.jLabel7.setText("In the past 2 weeks, how often " +mgr.BHM.TTMgr.getAnxiety(4));
                this.jLabel8.setText("In the past 2 weeks, how often " + mgr.BHM.TTMgr.getAnxiety(5));

                this.buttonGroup1.clearSelection();
                this.buttonGroup2.clearSelection();
                this.buttonGroup3.clearSelection();
                this.buttonGroup4.clearSelection();
                this.buttonGroup5.clearSelection();
                this.buttonGroup6.clearSelection();

            } else {
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f, "Answer all questions");
            }

        } else if (label.equalsIgnoreCase("Submit Anxiety Test")) {
            if ((this.buttonGroup1.isSelected(this.jRadioButton1.getModel()) || this.buttonGroup1.isSelected(this.jRadioButton2.getModel()) || this.buttonGroup1.isSelected(this.jRadioButton3.getModel()) || this.buttonGroup1.isSelected(this.jRadioButton4.getModel())) && (this.buttonGroup2.isSelected(this.jRadioButton5.getModel()) || this.buttonGroup2.isSelected(this.jRadioButton6.getModel()) || this.buttonGroup2.isSelected(this.jRadioButton7.getModel()) || this.buttonGroup2.isSelected(this.jRadioButton8.getModel())) && (this.buttonGroup3.isSelected(this.jRadioButton9.getModel()) || this.buttonGroup3.isSelected(this.jRadioButton10.getModel()) || this.buttonGroup3.isSelected(this.jRadioButton11.getModel()) || this.buttonGroup3.isSelected(this.jRadioButton12.getModel())) && (this.buttonGroup4.isSelected(this.jRadioButton13.getModel()) || this.buttonGroup4.isSelected(this.jRadioButton14.getModel()) || this.buttonGroup4.isSelected(this.jRadioButton15.getModel()) || this.buttonGroup4.isSelected(this.jRadioButton16.getModel())) && (this.buttonGroup5.isSelected(this.jRadioButton17.getModel()) || this.buttonGroup5.isSelected(this.jRadioButton18.getModel()) || this.buttonGroup5.isSelected(this.jRadioButton19.getModel()) || this.buttonGroup5.isSelected(this.jRadioButton20.getModel())) && (this.buttonGroup6.isSelected(this.jRadioButton21.getModel()) || this.buttonGroup6.isSelected(this.jRadioButton22.getModel()) || this.buttonGroup6.isSelected(this.jRadioButton23.getModel()) || this.buttonGroup6.isSelected(this.jRadioButton24.getModel()))) {
                if ((this.buttonGroup1.isSelected(this.jRadioButton1.getModel()))) {
                    Ansc += 3;
                } else if ((this.buttonGroup1.isSelected(this.jRadioButton2.getModel()))) {
                    Ansc += 2;
                } else if ((this.buttonGroup1.isSelected(this.jRadioButton3.getModel()))) {
                    Ansc += 1;
                } else if ((this.buttonGroup1.isSelected(this.jRadioButton4.getModel()))) {
                    Ansc += 0;
                }
                if ((this.buttonGroup2.isSelected(this.jRadioButton5.getModel()))) {
                    Ansc += 3;
                } else if ((this.buttonGroup2.isSelected(this.jRadioButton6.getModel()))) {
                    Ansc += 2;
                } else if ((this.buttonGroup2.isSelected(this.jRadioButton7.getModel()))) {
                    Ansc += 1;
                } else if ((this.buttonGroup2.isSelected(this.jRadioButton8.getModel()))) {
                    Ansc += 0;
                }
                if ((this.buttonGroup3.isSelected(this.jRadioButton9.getModel()))) {
                    Ansc += 3;
                } else if ((this.buttonGroup3.isSelected(this.jRadioButton10.getModel()))) {
                    Ansc += 2;
                } else if ((this.buttonGroup3.isSelected(this.jRadioButton11.getModel()))) {
                    Ansc += 1;
                } else if ((this.buttonGroup3.isSelected(this.jRadioButton12.getModel()))) {
                    Ansc += 0;
                }
                if ((this.buttonGroup4.isSelected(this.jRadioButton13.getModel()))) {
                    Ansc += 3;
                } else if ((this.buttonGroup4.isSelected(this.jRadioButton14.getModel()))) {
                    Ansc += 2;
                } else if ((this.buttonGroup4.isSelected(this.jRadioButton15.getModel()))) {
                    Ansc += 1;
                } else if ((this.buttonGroup4.isSelected(this.jRadioButton16.getModel()))) {
                    Ansc += 0;
                }
                if ((this.buttonGroup5.isSelected(this.jRadioButton17.getModel()))) {
                    Ansc += 3;
                } else if ((this.buttonGroup5.isSelected(this.jRadioButton18.getModel()))) {
                    Ansc += 2;
                } else if ((this.buttonGroup5.isSelected(this.jRadioButton19.getModel()))) {
                    Ansc += 1;
                } else if ((this.buttonGroup5.isSelected(this.jRadioButton20.getModel()))) {
                    Ansc += 0;
                }
                if ((this.buttonGroup6.isSelected(this.jRadioButton21.getModel()))) {
                    Ansc += 3;
                } else if ((this.buttonGroup6.isSelected(this.jRadioButton22.getModel()))) {
                    Ansc += 2;
                } else if ((this.buttonGroup6.isSelected(this.jRadioButton23.getModel()))) {
                    Ansc += 1;
                } else if ((this.buttonGroup6.isSelected(this.jRadioButton24.getModel()))) {
                    Ansc += 0;
                }

                this.jLabel1.setText("Depression test");
                take_test.setText("Submit Depression Test");
                this.jTextArea2.setText("Answer the questions below");
                this.jLabel3.setText("In last week, how often did you have:" + mgr.BHM.TTMgr.getDepression(0));
                this.jLabel4.setText("In last week, how often did you have:" + mgr.BHM.TTMgr.getDepression(1));
                this.jLabel5.setText("In last week, how often did you have:" + mgr.BHM.TTMgr.getDepression(2));
                this.jLabel6.setText("In last week, how often did you have:" + mgr.BHM.TTMgr.getDepression(3));
                this.jLabel7.setText("In last week, how often did you have:" + mgr.BHM.TTMgr.getDepression(4));
                this.jLabel8.setText("In last week, how often did you have:" + mgr.BHM.TTMgr.getDepression(5));

                this.buttonGroup1.clearSelection();
                this.buttonGroup2.clearSelection();
                this.buttonGroup3.clearSelection();
                this.buttonGroup4.clearSelection();
                this.buttonGroup5.clearSelection();
                this.buttonGroup6.clearSelection();

            } else {
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f, "Answer all questions");
            }

        }
        if (label.equalsIgnoreCase("Submit Depression Test")) {
            /*this.jTextArea1.setVisible(false);
        this.take_test.setVisible(false);
        this.jPanel4.setVisible(false);*/

            //this.jPanel2.add(this.jPanel6);
            if ((this.buttonGroup1.isSelected(this.jRadioButton1.getModel()) || this.buttonGroup1.isSelected(this.jRadioButton2.getModel()) || this.buttonGroup1.isSelected(this.jRadioButton3.getModel()) || this.buttonGroup1.isSelected(this.jRadioButton4.getModel())) && (this.buttonGroup2.isSelected(this.jRadioButton5.getModel()) || this.buttonGroup2.isSelected(this.jRadioButton6.getModel()) || this.buttonGroup2.isSelected(this.jRadioButton7.getModel()) || this.buttonGroup2.isSelected(this.jRadioButton8.getModel())) && (this.buttonGroup3.isSelected(this.jRadioButton9.getModel()) || this.buttonGroup3.isSelected(this.jRadioButton10.getModel()) || this.buttonGroup3.isSelected(this.jRadioButton11.getModel()) || this.buttonGroup3.isSelected(this.jRadioButton12.getModel())) && (this.buttonGroup4.isSelected(this.jRadioButton13.getModel()) || this.buttonGroup4.isSelected(this.jRadioButton14.getModel()) || this.buttonGroup4.isSelected(this.jRadioButton15.getModel()) || this.buttonGroup4.isSelected(this.jRadioButton16.getModel())) && (this.buttonGroup5.isSelected(this.jRadioButton17.getModel()) || this.buttonGroup5.isSelected(this.jRadioButton18.getModel()) || this.buttonGroup5.isSelected(this.jRadioButton19.getModel()) || this.buttonGroup5.isSelected(this.jRadioButton20.getModel())) && (this.buttonGroup6.isSelected(this.jRadioButton21.getModel()) || this.buttonGroup6.isSelected(this.jRadioButton22.getModel()) || this.buttonGroup6.isSelected(this.jRadioButton23.getModel()) || this.buttonGroup6.isSelected(this.jRadioButton24.getModel()))) {
                if ((this.buttonGroup1.isSelected(this.jRadioButton1.getModel()))) {
                    Desc += 3;
                } else if ((this.buttonGroup1.isSelected(this.jRadioButton2.getModel()))) {
                    Desc += 2;
                } else if ((this.buttonGroup1.isSelected(this.jRadioButton3.getModel()))) {
                    Desc += 1;
                } else if ((this.buttonGroup1.isSelected(this.jRadioButton4.getModel()))) {
                    Desc += 0;
                }
                if ((this.buttonGroup2.isSelected(this.jRadioButton5.getModel()))) {
                    Desc += 3;
                } else if ((this.buttonGroup2.isSelected(this.jRadioButton6.getModel()))) {
                    Desc += 2;
                } else if ((this.buttonGroup2.isSelected(this.jRadioButton7.getModel()))) {
                    Desc += 1;
                } else if ((this.buttonGroup2.isSelected(this.jRadioButton8.getModel()))) {
                    Desc += 0;
                }
                if ((this.buttonGroup3.isSelected(this.jRadioButton9.getModel()))) {
                    Desc += 3;
                } else if ((this.buttonGroup3.isSelected(this.jRadioButton10.getModel()))) {
                    Desc += 2;
                } else if ((this.buttonGroup3.isSelected(this.jRadioButton11.getModel()))) {
                    Desc += 1;
                } else if ((this.buttonGroup3.isSelected(this.jRadioButton12.getModel()))) {
                    Desc += 0;
                }
                if ((this.buttonGroup4.isSelected(this.jRadioButton13.getModel()))) {
                    Desc += 3;
                } else if ((this.buttonGroup4.isSelected(this.jRadioButton14.getModel()))) {
                    Desc += 2;
                } else if ((this.buttonGroup4.isSelected(this.jRadioButton15.getModel()))) {
                    Desc += 1;
                } else if ((this.buttonGroup4.isSelected(this.jRadioButton16.getModel()))) {
                    Desc += 0;
                }
                if ((this.buttonGroup5.isSelected(this.jRadioButton17.getModel()))) {
                    Desc += 3;
                } else if ((this.buttonGroup5.isSelected(this.jRadioButton18.getModel()))) {
                    Desc += 2;
                } else if ((this.buttonGroup5.isSelected(this.jRadioButton19.getModel()))) {
                    Desc += 1;
                } else if ((this.buttonGroup5.isSelected(this.jRadioButton20.getModel()))) {
                    Desc += 0;
                }
                if ((this.buttonGroup6.isSelected(this.jRadioButton21.getModel()))) {
                    Desc += 3;
                } else if ((this.buttonGroup6.isSelected(this.jRadioButton22.getModel()))) {
                    Desc += 2;
                } else if ((this.buttonGroup6.isSelected(this.jRadioButton23.getModel()))) {
                    Desc += 1;
                } else if ((this.buttonGroup6.isSelected(this.jRadioButton24.getModel()))) {
                    Desc += 0;
                }

                ent.setDepressionScore(Desc);
                ent.setAnxietyScore(Ansc);
                ent.setStressScore(Stsc);

                String feedback = mgr.BHM.TTMgr.feedback(ent.getStressScore(), ent.getAnxietyScore(), ent.getDepressionScore());
                /*String feedback = "";
            String opn = "";
        if(Stsc>=0 && Stsc<=18)
            opn+="You don't have any stress related disorder,";
        else if(Stsc>=18 && Stsc<=22)
            opn+="You are likely to have a mild stress disorder,";

        else if(Stsc>=22)
            opn+="You are likely to have a moderate stress disorder,";
        

        String op="";
        if(Desc>=0 && Desc<=10)
                op+="and minimal depression";
        else if(Desc>=11 && Desc<=16)
                op+="and mild depression";
        else if(Desc>=16 && Desc<=20)
                op+="and moderate depression";
        else
                op+="and severe depression";


        String opA = "";
        if(Ansc<10)
            opA+="mild anxiety ";
        else if(Ansc>=10 && Ansc<18)
            opA+="moderate anxiety ";
        else
            opA+="severe anxiety ";

        feedback = opn+opA+op;*/

                this.jLabel3.setText("Don't worry about the results, we are always by you to help you out");
                this.jLabel4.setVisible(false);
                this.jLabel5.setVisible(false);
                this.jLabel6.setVisible(false);
                this.jLabel7.setVisible(false);
                this.jLabel8.setVisible(false);

                this.jRadioButton1.setVisible(false);
                this.jRadioButton2.setVisible(false);
                this.jRadioButton3.setVisible(false);
                this.jRadioButton4.setVisible(false);
                this.jRadioButton5.setVisible(false);
                this.jRadioButton6.setVisible(false);
                this.jRadioButton7.setVisible(false);
                this.jRadioButton8.setVisible(false);
                this.jRadioButton9.setVisible(false);
                this.jRadioButton10.setVisible(false);
                this.jRadioButton11.setVisible(false);
                this.jRadioButton12.setVisible(false);
                this.jRadioButton13.setVisible(false);
                this.jRadioButton14.setVisible(false);
                this.jRadioButton15.setVisible(false);
                this.jRadioButton16.setVisible(false);
                this.jRadioButton17.setVisible(false);
                this.jRadioButton18.setVisible(false);
                this.jRadioButton19.setVisible(false);
                this.jRadioButton20.setVisible(false);
                this.jRadioButton21.setVisible(false);
                this.jRadioButton22.setVisible(false);
                this.jRadioButton23.setVisible(false);
                this.jRadioButton24.setVisible(false);

                this.jLabel1.setText("Test Results");

                this.take_test.setText("Give preferences");
                /*this.take_test.setLocation(300,450);
            this.jPanel6.revalidate();
            this.jPanel6.repaint();*/
                //this.jPanel6.add(new JLabel(" "))
                this.jTextArea2.setVisible(true);
                this.jTextArea2.setText(feedback);

            }
             else {
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f, "Answer all questions");
            }

        }
        if (label.equalsIgnoreCase("Give preferences")) {
                mgr.showPU();
         }

    }//GEN-LAST:event_take_testMouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        mgr.showMMU();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        mgr.showMMU();
    }//GEN-LAST:event_jLabel11MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton take_test;
    // End of variables declaration//GEN-END:variables
}
